# Generated by Django 4.1.7 on 2023-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produto_id',
            field=models.IntegerField(),
        ),
    ]
