# Generated by Django 4.1.7 on 2023-06-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_produto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produto_id',
        ),
    ]
