# Generated by Django 4.1.7 on 2023-06-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_produto_produto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
