# Generated by Django 4.1.7 on 2023-06-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
