# Generated by Django 4.1.7 on 2023-06-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_pedido_cliente_pedido_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
