# Generated by Django 4.1.7 on 2023-06-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
