# Generated by Django 4.1.7 on 2023-06-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_cliente_pedido_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
            preserve_default=False,
        ),
    ]
