# Generated by Django 4.1.7 on 2023-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_pedido_cliente_id_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
